# Generated by Django 4.1.7 on 2023-02-26 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.URLField()),
                ('url', models.URLField()),
                ('host', models.URLField(default='https://social-distribution-media.herokuapp.com/')),
                ('displayName', models.TextField(default=None)),
                ('github', models.URLField()),
                ('profileImage', models.URLField()),
                ('followers', models.ManyToManyField(blank=True, to='api.author')),
            ],
        ),
    ]
