# Generated by Django 4.1.7 on 2023-02-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(max_length=20)),
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('host', models.URLField()),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('profile_image', models.URLField()),
            ],
        ),
    ]
