# Generated by Django 4.1.7 on 2023-02-26 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://social-distribution-media.herokuapp.com', editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(blank=True, default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, default=None, editable=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, default=None, editable=False)),
                ('title', models.TextField()),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.TextField()),
                ('contentType', models.TextField()),
                ('content', models.TextField()),
                ('categories', models.JSONField()),
                ('count', models.IntegerField()),
                ('comments', models.URLField()),
                ('commentsSrc', models.JSONField()),
                ('published', models.DateTimeField()),
                ('visibility', models.TextField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], default='FRIENDS')),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
