# Generated by Django 4.1.7 on 2023-03-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://social-distribution-media.herokuapp.com/api'),
        ),
    ]
