# Generated by Django 4.1.7 on 2023-03-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment__post_author_id_comment__post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='object_id',
        ),
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
