# Generated by Django 4.1.7 on 2023-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.TextField(choices=[('text/markdown', 'Common mark'), ('text/plain', 'UTF-8 plain text'), ('application/base64', 'Base 64 string'), ('image/png;base64', 'Base 64 string of PNG image'), ('image/jpeg;base64', 'Base 64 string of JPEG image'), ('image/jpg;base64', 'Base 64 string of JPG image')], default='text/plain'),
        ),
    ]
