# Generated by Django 4.1.7 on 2023-02-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_author_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.JSONField(default=list),
        ),
    ]
