# Generated by Django 4.1.7 on 2023-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_content_alter_post_contenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='commentsSrc',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
