# Generated by Django 4.1.7 on 2023-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_author_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_image',
            new_name='profileImage',
        ),
        migrations.RemoveField(
            model_name='author',
            name='display_name',
        ),
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
