# Generated by Django 4.1.7 on 2023-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_profile_image_author_profileimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(to='api.author'),
        ),
    ]
