# Generated by Django 4.1.7 on 2023-03-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_author_following_alter_author_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='fromAuthor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='toAuthor',
            new_name='object',
        ),
        migrations.AddField(
            model_name='follow',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
