# Generated by Django 4.1.7 on 2023-02-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_commentssrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentsSrc',
        ),
    ]
