# Generated by Django 4.1.7 on 2023-03-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_allowlist_allowednode_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowednode',
            old_name='ip_addr',
            new_name='ip',
        ),
    ]
