# Generated by Django 4.1.7 on 2023-03-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_remotenoderequest_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotenoderequest',
            old_name='detail',
            new_name='group',
        ),
        migrations.AddField(
            model_name='remotenoderequest',
            name='discord',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotenoderequest',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
