# Generated by Django 4.1.7 on 2023-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_remotenoderequest_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenoderequest',
            name='host',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
