# Generated by Django 4.1.7 on 2023-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_allowedremotenode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
