# Generated by Django 4.1.7 on 2023-03-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedLocalNode',
        ),
        migrations.DeleteModel(
            name='RemoteNodeRequest',
        ),
    ]
