run:
	python manage.py runserver

db:
	python manage.py makemigrations
	python manage.py migrate

test:
	python manage.py test

super:
	python manage.py createsuperuser

flush:
# DELETES ENTIRE DB
	python manage.py flush
