# Generated by Django 4.1.7 on 2023-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_follow_toauthor_alter_follow_fromauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.post'),
        ),
    ]
