# Generated by Django 4.1.7 on 2023-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remotenoderequest_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenoderequest',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
