# Generated by Django 4.1.7 on 2023-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_allowednode_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowednode',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
