# Generated by Django 4.1.7 on 2023-03-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_allowednode_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowednode',
            name='ip',
        ),
    ]
