# Generated by Django 4.1.7 on 2023-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_allowednode_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRemoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AllowedNode',
            new_name='AllowedLocalNode',
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://social-distribution-media.herokuapp.com'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
