# Generated by Django 4.1.7 on 2023-03-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_author_type_delete_allowedremotenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='_post_author_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='_post_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.URLField(blank=True, default=None),
        ),
    ]
