# Generated by Django 4.1.7 on 2023-03-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_comment__post_author_id_alter_comment__post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedremotenode',
            name='user',
        ),
    ]
