name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build app
        working-directory: ./frontend
        run: npm run relocate

      - name: Check if changed
        id: diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit built files
        if: steps.diff.outputs.changed == 'true'
        with:
          token: ${{ secrets.TEMP_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build app for Heroku deployment"
          git push

      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "social-distribution-media" #Must be unique in Heroku
          heroku_email: "jboileau@ualberta.ca"
          appdir: "backend"
