name: Build and push to Heroku branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Commit built files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build app for Heroku deployment"
          git branch -M main

      - name: Push to Heroku branch
        uses: ad-m/github-push-action@master
        with:
          branch: heroku
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
